# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20161012_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='attached_file',
            field=models.FileField(blank=True, upload_to=b'files'),
        ),
    ]
