# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_admincomment_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admincomment',
            name='ticket',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tickets.Ticket'),
        ),
    ]
