# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20161008_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admincomment',
            name='ticket',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='tickets.Ticket'),
        ),
    ]
