# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 21:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_usercomment_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admincomment',
            name='ticket',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='admin_comments', to='tickets.Ticket'),
        ),
        migrations.AlterField(
            model_name='admincomment',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='ticket',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to='tickets.Ticket'),
        ),
    ]
