# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20161009_0028'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admincomment',
            table='AdminComment',
        ),
    ]
