# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_auto_20161009_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercomment',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='usercomment',
            name='text',
        ),
        migrations.RemoveField(
            model_name='usercomment',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='usercomment',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='ava',
            field=models.ImageField(blank=True, upload_to=b'avatars'),
        ),
        migrations.AlterField(
            model_name='admincomment',
            name='ticket',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='admincomments', to='tickets.Ticket'),
        ),
        migrations.AlterModelTable(
            name='usercomment',
            table='UserComment',
        ),
    ]
