# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_admincomment_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admincomment',
            name='file',
        ),
        migrations.AddField(
            model_name='admincomment',
            name='attached_file',
            field=models.FileField(blank=True, upload_to=b'file'),
        ),
    ]
