# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_auto_20161010_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admincomment',
            name='attached_file',
            field=models.FileField(upload_to=b''),
        ),
    ]
